import type { GuideLesson } from "@/lib/guides/types";

export const javaGuides: GuideLesson[] = [
  {
    slug: "introduction",
    topicId: "java",
    title: "Introduction to Java",
    summary: "What Java is, JVM, and your first class.",
    minutes: 10,
    order: 1,
    blocks: [
      { type: "p", text: "Java is an object-oriented language that runs on the Java Virtual Machine (JVM). Write once, run anywhere — the same bytecode runs on Windows, Mac, and Linux." },
      { type: "p", text: "Every Java program starts in a class with a main method. File name must match the public class name." },
      { type: "code", caption: "HelloWorld.java", code: 'public class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println("Hello, Java!");\n    }\n}' },
      { type: "p", text: "Compile with javac HelloWorld.java, run with java HelloWorld." },
    ],
  },
  {
    slug: "variables-and-types",
    topicId: "java",
    title: "Variables and Data Types",
    summary: "Primitives, strings, and declaring variables.",
    minutes: 12,
    order: 2,
    blocks: [
      { type: "p", text: "Java is statically typed — every variable has a type declared upfront." },
      { type: "code", code: 'int age = 20;\ndouble price = 9.99;\nboolean active = true;\nString name = "Alex";\n\nfinal int MAX = 100; // cannot change' },
      { type: "p", text: "Primitives: byte, short, int, long, float, double, char, boolean. String is a class, not a primitive." },
    ],
  },
  {
    slug: "operators",
    topicId: "java",
    title: "Operators",
    summary: "Arithmetic, comparison, and logical operators.",
    minutes: 8,
    order: 3,
    blocks: [
      { type: "code", code: "int a = 10, b = 3;\nSystem.out.println(a + b);\nSystem.out.println(a % b);\nSystem.out.println(a > b);" },
      { type: "p", text: "String concatenation uses +. For objects, use .equals() instead of == to compare content." },
      { type: "code", code: 'String s1 = "hi";\nString s2 = "hi";\nSystem.out.println(s1.equals(s2)); // true' },
    ],
  },
  {
    slug: "control-flow",
    topicId: "java",
    title: "Control Flow",
    summary: "if, switch, for, while, and break.",
    minutes: 14,
    order: 4,
    blocks: [
      { type: "code", code: 'int score = 85;\n\nif (score >= 90) {\n    System.out.println("A");\n} else if (score >= 80) {\n    System.out.println("B");\n} else {\n    System.out.println("C");\n}' },
      { type: "code", caption: "for loop", code: "for (int i = 0; i < 5; i++) {\n    System.out.println(i);\n}" },
      { type: "code", caption: "enhanced for", code: 'String[] fruits = {"apple", "banana"};\nfor (String fruit : fruits) {\n    System.out.println(fruit);\n}' },
    ],
  },
  {
    slug: "methods",
    topicId: "java",
    title: "Methods",
    summary: "Define reusable logic with parameters and return types.",
    minutes: 12,
    order: 5,
    blocks: [
      { type: "code", code: 'public static int add(int a, int b) {\n    return a + b;\n}\n\npublic static void greet(String name) {\n    System.out.println("Hello, " + name);\n}' },
      { type: "p", text: "void means no return value. static methods belong to the class — you can call them without creating an object." },
    ],
  },
  {
    slug: "classes-and-objects",
    topicId: "java",
    title: "Classes and Objects",
    summary: "Create blueprints and instances.",
    minutes: 14,
    order: 6,
    blocks: [
      { type: "code", code: 'public class Player {\n    String name;\n    int level;\n\n    public Player(String name, int level) {\n        this.name = name;\n        this.level = level;\n    }\n\n    public void levelUp() {\n        level++;\n    }\n}\n\nPlayer p = new Player("Mia", 1);\np.levelUp();' },
      { type: "p", text: "A class is a blueprint. new creates an object (instance). Fields hold data, methods define behavior." },
    ],
  },
  {
    slug: "arrays",
    topicId: "java",
    title: "Arrays",
    summary: "Fixed-size collections and ArrayList.",
    minutes: 10,
    order: 7,
    blocks: [
      { type: "code", code: 'int[] nums = {1, 2, 3};\nSystem.out.println(nums.length);\nSystem.out.println(nums[0]);' },
      { type: "p", text: "ArrayList is resizable. Import java.util.ArrayList:" },
      { type: "code", code: 'ArrayList<String> items = new ArrayList<>();\nitems.add("sword");\nitems.add("shield");\nSystem.out.println(items.get(0));' },
    ],
  },
  {
    slug: "inheritance",
    topicId: "java",
    title: "Inheritance",
    summary: "Extend classes and override methods.",
    minutes: 12,
    order: 8,
    blocks: [
      { type: "code", code: 'public class Animal {\n    void speak() {\n        System.out.println("...");\n    }\n}\n\npublic class Dog extends Animal {\n    @Override\n    void speak() {\n        System.out.println("Woof!");\n    }\n}' },
      { type: "p", text: "extends creates a child class. @Override replaces a parent method. super calls the parent version." },
    ],
  },
  {
    slug: "encapsulation",
    topicId: "java",
    title: "Encapsulation",
    summary: "private fields, getters, and setters.",
    minutes: 10,
    order: 9,
    blocks: [
      { type: "code", code: 'public class Account {\n    private double balance;\n\n    public double getBalance() {\n        return balance;\n    }\n\n    public void deposit(double amount) {\n        if (amount > 0) balance += amount;\n    }\n}' },
      { type: "p", text: "Hide internal data with private. Expose controlled access through public methods. This protects your object from invalid changes." },
    ],
  },
  {
    slug: "exceptions",
    topicId: "java",
    title: "Exception Handling",
    summary: "try, catch, finally, and throwing errors.",
    minutes: 10,
    order: 10,
    blocks: [
      { type: "code", code: 'try {\n    int result = 10 / 0;\n} catch (ArithmeticException e) {\n    System.out.println("Cannot divide by zero");\n} finally {\n    System.out.println("Done");\n}' },
      { type: "p", text: "Checked exceptions must be handled or declared. Use throw to raise your own errors when rules are broken." },
    ],
  },
];
