import type { GuideLesson } from "@/lib/guides/types";

export const javascriptGuides: GuideLesson[] = [
  {
    slug: "introduction",
    topicId: "javascript",
    title: "Introduction to JavaScript",
    summary: "What JS is, where it runs, and your first script.",
    minutes: 8,
    order: 1,
    blocks: [
      { type: "p", text: "JavaScript is the language of the web. It runs in every browser and can also run on servers (Node.js). It makes pages interactive — buttons, forms, animations, and data updates without reloading." },
      { type: "code", caption: "Browser console", code: 'console.log("Hello from JavaScript!");' },
      { type: "p", text: "You can put JS inside <script> tags in HTML or in a separate .js file. Statements end with semicolons (optional but recommended)." },
      { type: "ul", items: ["JS is case-sensitive", "Use // for single-line comments", "Use /* */ for multi-line comments"] },
    ],
  },
  {
    slug: "variables-and-types",
    topicId: "javascript",
    title: "Variables: let, const, and Types",
    summary: "Declare variables and understand JS data types.",
    minutes: 12,
    order: 2,
    blocks: [
      { type: "p", text: "Use let for values that change, const for values that stay fixed. Avoid var in modern code." },
      { type: "code", code: 'let score = 0;\nconst appName = "CodeQuest";\nscore = 10;\n\nlet name = "Jordan";\nlet active = true;\nlet price = 9.99;' },
      { type: "p", text: "Main types: number, string, boolean, undefined, null, object, symbol, bigint. typeof tells you the type." },
      { type: "code", code: 'console.log(typeof name);     // "string"\nconsole.log(typeof score);    // "number"' },
    ],
  },
  {
    slug: "operators",
    topicId: "javascript",
    title: "Operators and Expressions",
    summary: "Math, strings, comparisons, and logical operators.",
    minutes: 10,
    order: 3,
    blocks: [
      { type: "code", code: 'let a = 10, b = 3;\nconsole.log(a + b);  // 13\nconsole.log(a % b);  // 1' },
      { type: "p", text: "Strings join with +. Template literals use backticks for embedded expressions:" },
      { type: "code", code: 'let user = "Mia";\nconsole.log(`Hello, ${user}!`);' },
      { type: "p", text: "Comparisons: === and !== check value AND type. Prefer === over == to avoid surprises." },
      { type: "code", code: 'console.log(5 === "5");  // false\nconsole.log(5 == "5");   // true (avoid this)' },
    ],
  },
  {
    slug: "conditionals",
    topicId: "javascript",
    title: "Conditionals",
    summary: "if, else if, else, and the ternary operator.",
    minutes: 10,
    order: 4,
    blocks: [
      { type: "code", code: 'let temp = 32;\n\nif (temp > 30) {\n  console.log("Hot");\n} else if (temp > 20) {\n  console.log("Warm");\n} else {\n  console.log("Cool");\n}' },
      { type: "p", text: "Ternary is a one-line if/else:" },
      { type: "code", code: 'let score = 75;\nlet status = score >= 60 ? "Pass" : "Fail";' },
      { type: "p", text: "switch works well when comparing one value against many options." },
    ],
  },
  {
    slug: "loops",
    topicId: "javascript",
    title: "Loops",
    summary: "for, while, for...of, and break/continue.",
    minutes: 12,
    order: 5,
    blocks: [
      { type: "code", code: "for (let i = 0; i < 5; i++) {\n  console.log(i);\n}" },
      { type: "code", caption: "for...of with arrays", code: 'const colors = ["red", "green", "blue"];\nfor (const color of colors) {\n  console.log(color);\n}' },
      { type: "code", caption: "while", code: "let n = 3;\nwhile (n > 0) {\n  console.log(n);\n  n--;\n}" },
    ],
  },
  {
    slug: "functions",
    topicId: "javascript",
    title: "Functions",
    summary: "Declarations, arrow functions, and parameters.",
    minutes: 14,
    order: 6,
    blocks: [
      { type: "code", code: 'function add(a, b) {\n  return a + b;\n}\n\nconst multiply = (a, b) => a * b;\n\nconsole.log(add(2, 3));\nconsole.log(multiply(4, 5));' },
      { type: "p", text: "Arrow functions are shorter. Default parameters work like Python:" },
      { type: "code", code: 'const greet = (name = "Guest") => `Hi, ${name}`;' },
    ],
  },
  {
    slug: "arrays",
    topicId: "javascript",
    title: "Arrays",
    summary: "Create, access, and transform lists of data.",
    minutes: 12,
    order: 7,
    blocks: [
      { type: "code", code: 'const nums = [1, 2, 3];\nnums.push(4);\nconsole.log(nums.length);\nconsole.log(nums[0]);' },
      { type: "p", text: "Useful methods: map, filter, find, reduce, includes, slice, splice." },
      { type: "code", code: 'const doubled = nums.map(n => n * 2);\nconst evens = nums.filter(n => n % 2 === 0);' },
    ],
  },
  {
    slug: "objects",
    topicId: "javascript",
    title: "Objects",
    summary: "Key-value data and destructuring.",
    minutes: 12,
    order: 8,
    blocks: [
      { type: "code", code: 'const user = {\n  name: "Alex",\n  age: 20,\n  greet() {\n    return `I am ${this.name}`;\n  }\n};\n\nconsole.log(user.name);\nconsole.log(user.greet());' },
      { type: "p", text: "Destructuring pulls values out quickly:" },
      { type: "code", code: 'const { name, age } = user;\nconst [first, second] = nums;' },
    ],
  },
  {
    slug: "dom-basics",
    topicId: "javascript",
    title: "DOM Basics",
    summary: "Select elements and respond to user events.",
    minutes: 14,
    order: 9,
    blocks: [
      { type: "p", text: "The DOM is the page structure the browser builds from HTML. JavaScript can read and change it." },
      { type: "code", code: 'const btn = document.querySelector("#myButton");\nconst title = document.getElementById("title");\n\ntitle.textContent = "Updated!";\nbtn.addEventListener("click", () => {\n  alert("Clicked!");\n});' },
      { type: "p", text: "Common tasks: change text, add/remove classes, create elements, handle clicks and form submits." },
    ],
  },
  {
    slug: "async-basics",
    topicId: "javascript",
    title: "Async JavaScript",
    summary: "Promises, async/await, and fetching data.",
    minutes: 14,
    order: 10,
    blocks: [
      { type: "p", text: "Some operations take time (network requests, timers). async/await lets you write async code that reads like normal code." },
      { type: "code", code: 'async function loadData() {\n  const response = await fetch("/api/users");\n  const data = await response.json();\n  console.log(data);\n}' },
      { type: "p", text: "Always handle errors with try/catch when fetching data." },
    ],
  },
];
