import type { GuideLesson } from "@/lib/guides/types";

const PRACTICE_NOTE =
  "Scroll to Practice this lesson below when you're ready. Read first, then type the code yourself — that's how it sticks.";

export const pythonGuides: GuideLesson[] = [
  {
    slug: "introduction",
    topicId: "python",
    title: "Introduction to Python",
    summary: "What Python is, how to run code, and your first program.",
    minutes: 8,
    order: 1,
    blocks: [
      { type: "p", text: "Python is a popular programming language known for readable syntax. It is used for websites, data science, automation, games, and more. Many beginners start here because the code looks close to plain English." },
      { type: "p", text: "A Python program is a file ending in .py. You run it with python filename.py. The computer reads your instructions from top to bottom." },
      { type: "code", caption: "Your first program", code: 'print("Hello, World!")\nprint("Welcome to Python")' },
      { type: "p", text: "print() displays text on the screen. Text inside quotes is called a string. Each line is one instruction." },
      { type: "ul", items: ["Python uses indentation (spaces) to group code blocks", "Comments start with # and are ignored by the computer", "Python is case-sensitive: Name and name are different"] },
      {
        type: "steps",
        title: "How to read the example",
        items: [
          "print() is a command that shows text on the screen.",
          "Text inside quotes is a string — a piece of text.",
          "Each line is one instruction; Python runs them top to bottom.",
        ],
      },
      { type: "tip", title: "Ready to try?", text: PRACTICE_NOTE },
    ],
  },
  {
    slug: "variables-and-types",
    topicId: "python",
    title: "Variables and Data Types",
    summary: "Store values, name them, and understand int, float, str, and bool.",
    minutes: 12,
    order: 2,
    blocks: [
      { type: "p", text: "A variable is a named box that holds a value. You create one with = (assignment). The name goes on the left, the value on the right." },
      { type: "code", code: 'name = "Alex"\nage = 16\nheight = 1.72\nis_student = True\n\nprint(name)\nprint(age)' },
      { type: "p", text: "Common types in Python:" },
      { type: "ul", items: ["int — whole numbers like 0, 42, -7", "float — decimal numbers like 3.14", "str — text in quotes", "bool — True or False"] },
      { type: "code", caption: "Check a type", code: 'x = 10\nprint(type(x))  # <class \'int\'>\n\ny = "hello"\nprint(type(y))  # <class \'str\'>' },
      { type: "p", text: "You can change what a variable holds by assigning again. The old value is replaced." },
      { type: "tip", title: "Practice", text: PRACTICE_NOTE },
    ],
  },
  {
    slug: "operators",
    topicId: "python",
    title: "Operators and Expressions",
    summary: "Math, comparisons, and combining values.",
    minutes: 10,
    order: 3,
    blocks: [
      { type: "p", text: "Python supports standard math: + - * / // % **. Use // for integer division and % for remainder." },
      { type: "code", code: "a = 10\nb = 3\nprint(a + b)   # 13\nprint(a // b)  # 3\nprint(a % b)   # 1\nprint(a ** b)  # 1000" },
      { type: "p", text: "Comparison operators return True or False: == != < > <= >=" },
      { type: "code", code: 'print(5 > 3)    # True\nprint(5 == "5") # False — different types' },
      { type: "p", text: "Logical operators combine conditions: and, or, not." },
      { type: "code", code: "age = 20\nhas_id = True\nprint(age >= 18 and has_id)  # True" },
      { type: "tip", title: "Practice", text: PRACTICE_NOTE },
    ],
  },
  {
    slug: "conditionals",
    topicId: "python",
    title: "Conditionals (if / elif / else)",
    summary: "Make decisions in your program.",
    minutes: 12,
    order: 4,
    blocks: [
      { type: "p", text: "Use if to run code only when a condition is True. elif checks another condition. else runs when nothing matched." },
      { type: "code", caption: "Grading example", code: 'score = 85\n\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelif score >= 70:\n    print("C")\nelse:\n    print("Keep practicing")' },
      { type: "p", text: "Indentation matters! The code under if must be indented (usually 4 spaces). All lines at the same indent level belong to the same block." },
      { type: "p", text: "You can nest if statements inside other blocks for more complex logic." },
      {
        type: "steps",
        title: "How if / elif / else works",
        items: [
          "if — runs when the condition is True.",
          "elif — checks another condition if the first failed.",
          "else — runs when nothing above matched.",
        ],
      },
      { type: "tip", title: "Practice", text: PRACTICE_NOTE },
    ],
  },
  {
    slug: "loops",
    topicId: "python",
    title: "Loops (for and while)",
    summary: "Repeat actions without copying code.",
    minutes: 14,
    order: 5,
    blocks: [
      { type: "p", text: "A for loop repeats once for each item in a sequence." },
      { type: "code", code: 'fruits = ["apple", "banana", "cherry"]\nfor fruit in fruits:\n    print(fruit)' },
      { type: "p", text: "range(n) gives numbers 0 to n-1. range(1, 6) gives 1 through 5." },
      { type: "code", code: "for i in range(1, 6):\n    print(i * i)" },
      { type: "p", text: "A while loop repeats as long as a condition stays True. Always make sure the condition can become False, or you get an infinite loop." },
      { type: "code", code: "count = 0\nwhile count < 3:\n    print(count)\n    count += 1" },
      { type: "ul", items: ["break — exit the loop early", "continue — skip to the next iteration"] },
      { type: "tip", title: "Practice", text: PRACTICE_NOTE },
    ],
  },
  {
    slug: "functions",
    topicId: "python",
    title: "Functions",
    summary: "Define reusable blocks of code with parameters and return values.",
    minutes: 14,
    order: 6,
    blocks: [
      { type: "p", text: "A function is a named recipe. You define it with def, call it by name with ()." },
      { type: "code", code: 'def greet(name):\n    return f"Hello, {name}!"\n\nmessage = greet("Sam")\nprint(message)' },
      { type: "p", text: "Parameters are inputs. return sends a value back to the caller. A function without return gives None." },
      { type: "code", caption: "Default parameter", code: 'def power(base, exponent=2):\n    return base ** exponent\n\nprint(power(3))     # 9\nprint(power(3, 3))  # 27' },
      { type: "p", text: "Keep functions small and focused. One function should do one clear job." },
      { type: "tip", title: "Practice", text: PRACTICE_NOTE },
    ],
  },
  {
    slug: "lists-and-tuples",
    topicId: "python",
    title: "Lists and Tuples",
    summary: "Store collections of values.",
    minutes: 12,
    order: 7,
    blocks: [
      { type: "p", text: "A list holds multiple values in order. Lists are mutable — you can change them." },
      { type: "code", code: 'nums = [10, 20, 30]\nnums.append(40)\nnums[0] = 5\nprint(nums)       # [5, 20, 30, 40]\nprint(len(nums))  # 4' },
      { type: "p", text: "Common list methods: append, remove, pop, sort, reverse. Slicing gets a sub-list: items[1:3]." },
      { type: "p", text: "A tuple is like a list but cannot be changed after creation. Use () instead of []:" },
      { type: "code", code: 'point = (3, 7)\nprint(point[0])  # 3' },
      { type: "tip", title: "Practice", text: PRACTICE_NOTE },
    ],
  },
  {
    slug: "dictionaries",
    topicId: "python",
    title: "Dictionaries",
    summary: "Key-value pairs for fast lookups.",
    minutes: 10,
    order: 8,
    blocks: [
      { type: "p", text: "A dictionary maps keys to values. Keys must be unique. Great for records, settings, and counting." },
      { type: "code", code: 'student = {\n    "name": "Mia",\n    "age": 17,\n    "course": "Python"\n}\n\nprint(student["name"])\nstudent["age"] = 18' },
      { type: "p", text: "Loop over keys, values, or both:" },
      { type: "code", code: 'for key, value in student.items():\n    print(key, "->", value)' },
      { type: "tip", title: "Practice", text: PRACTICE_NOTE },
    ],
  },
  {
    slug: "file-handling",
    topicId: "python",
    title: "File Handling",
    summary: "Read and write text files.",
    minutes: 10,
    order: 9,
    blocks: [
      { type: "p", text: "Use with open(...) as file: to safely open files. The file closes automatically when the block ends." },
      { type: "code", code: 'with open("notes.txt", "w") as f:\n    f.write("Line one\\n")\n    f.write("Line two\\n")' },
      { type: "code", caption: "Reading", code: 'with open("notes.txt", "r") as f:\n    content = f.read()\n    print(content)' },
      { type: "p", text: "Modes: r read, w write (overwrites), a append. Always handle the case where a file might not exist." },
      {
        type: "steps",
        title: "File handling flow",
        items: [
          "Open with with open(path, mode) as f — the file closes automatically.",
          "Read with f.read() or loop line by line.",
          "Write with f.write(text) — add \\n yourself for new lines.",
        ],
      },
      { type: "tip", title: "Practice", text: PRACTICE_NOTE },
    ],
  },
  {
    slug: "error-handling",
    topicId: "python",
    title: "Error Handling",
    summary: "try, except, and writing safer programs.",
    minutes: 10,
    order: 10,
    blocks: [
      { type: "p", text: "When something goes wrong, Python raises an exception. Use try/except to catch it and respond gracefully instead of crashing." },
      { type: "code", code: 'try:\n    age = int(input("Enter age: "))\n    print("You are", age)\nexcept ValueError:\n    print("Please enter a valid number")' },
      { type: "p", text: "You can catch specific error types. A finally block always runs for cleanup." },
      { type: "ul", items: ["ValueError — bad conversion or value", "TypeError — wrong type used", "FileNotFoundError — missing file", "ZeroDivisionError — divide by zero"] },
      { type: "tip", title: "Practice", text: PRACTICE_NOTE },
    ],
  },
  {
    slug: "time-complexity",
    topicId: "python",
    title: "Time Complexity (Big O)",
    summary: "Why efficient code matters — and how Arena checks it.",
    minutes: 12,
    order: 11,
    blocks: [
      { type: "p", text: "Time complexity describes how runtime grows as input size grows. We write it with Big O notation: O(1), O(n), O(n²), and so on." },
      { type: "ul", items: ["O(1) — constant time, size barely matters", "O(n) — one pass over n items (a single loop)", "O(n²) — nested loops over the same data — often too slow for large inputs"] },
      { type: "code", caption: "O(n) — one loop", code: "def count_vowels(text):\n    total = 0\n    for ch in text.lower():\n        if ch in \"aeiou\":\n            total += 1\n    return total" },
      { type: "code", caption: "O(n²) — avoid on big strings", code: "def slow_count(text):\n    total = 0\n    for i in range(len(text)):\n        for j in range(len(text)):\n            if text[i].lower() in \"aeiou\":\n                total += 1\n                break\n    return total" },
      { type: "p", text: "In Dev Ladder Arena, visible tests use small inputs. Expert challenges also run hidden large-input checks. Brute-force O(n²) code may pass tiny tests but fail with Time limit exceeded on big data — just like coding interviews." },
      { type: "p", text: "Rule of thumb: if you loop inside another loop over the same collection, ask yourself if one pass is enough." },
      {
        type: "steps",
        title: "How to think in Big O",
        items: [
          "One loop over n items → usually O(n).",
          "Loop inside another loop on the same data → often O(n²).",
          "In Arena, hidden large tests catch slow solutions — aim for one pass when you can.",
        ],
      },
      { type: "tip", title: "Practice", text: PRACTICE_NOTE },
    ],
  },
];
