import type { GuideLesson } from "@/lib/guides/types";

export const reactGuides: GuideLesson[] = [
  {
    slug: "introduction",
    topicId: "react",
    title: "What is React?",
    summary: "Components, the virtual DOM, and why React exists.",
    minutes: 10,
    order: 1,
    blocks: [
      { type: "p", text: "React is a JavaScript library for building user interfaces. Instead of updating the page manually, you describe what the UI should look like for a given state — React figures out the changes." },
      { type: "p", text: "Everything in React is a component — a reusable piece of UI. A page might be built from a Header, Sidebar, and Card components." },
      { type: "ul", items: ["Component-based — build once, reuse everywhere", "Declarative — describe the result, not the steps", "Virtual DOM — efficient updates", "Huge ecosystem — tools, libraries, jobs"] },
      { type: "code", caption: "Minimal example", code: 'import { createRoot } from "react-dom/client";\n\nfunction App() {\n  return <h1>Hello React</h1>;\n}\n\ncreateRoot(document.getElementById("root")).render(<App />);' },
    ],
  },
  {
    slug: "jsx",
    topicId: "react",
    title: "JSX",
    summary: "HTML-like syntax inside JavaScript.",
    minutes: 12,
    order: 2,
    blocks: [
      { type: "p", text: "JSX looks like HTML but lives inside JavaScript. It must return one parent element (or use a Fragment <>...</>)." },
      { type: "code", code: 'function Profile() {\n  const name = "Sam";\n  return (\n    <div className="card">\n      <h2>{name}</h2>\n      <p>Level 5</p>\n    </div>\n  );\n}' },
      { type: "p", text: "Rules: use className instead of class, camelCase for attributes (onClick), and {} for JavaScript expressions." },
      { type: "p", text: "JSX compiles to JavaScript function calls. That is why you need a build tool like Vite or Next.js." },
    ],
  },
  {
    slug: "components",
    topicId: "react",
    title: "Components",
    summary: "Function components, composition, and file structure.",
    minutes: 12,
    order: 3,
    blocks: [
      { type: "p", text: "A component is a function that returns JSX. Name components with PascalCase." },
      { type: "code", code: 'function Button({ label }) {\n  return <button>{label}</button>;\n}\n\nfunction Page() {\n  return (\n    <main>\n      <Button label="Save" />\n      <Button label="Cancel" />\n    </main>\n  );\n}' },
      { type: "p", text: "Composition means building big UIs from small parts. Each component should have one clear job." },
    ],
  },
  {
    slug: "props",
    topicId: "react",
    title: "Props",
    summary: "Pass data from parent to child components.",
    minutes: 12,
    order: 4,
    blocks: [
      { type: "p", text: "Props are read-only inputs to a component. The parent passes them; the child uses them." },
      { type: "code", code: 'function UserCard({ name, level, avatar }) {\n  return (\n    <article>\n      <img src={avatar} alt={name} />\n      <h3>{name}</h3>\n      <p>Level {level}</p>\n    </article>\n  );\n}\n\n<UserCard name="Mia" level={12} avatar="/mia.png" />' },
      { type: "p", text: "Props flow down only. A child cannot change its parent's data directly." },
    ],
  },
  {
    slug: "state",
    topicId: "react",
    title: "State with useState",
    summary: "Data that changes over time inside a component.",
    minutes: 14,
    order: 5,
    blocks: [
      { type: "p", text: "State is memory inside a component. When state changes, React re-renders the component." },
      { type: "code", code: 'import { useState } from "react";\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount(count + 1)}>+1</button>\n    </div>\n  );\n}' },
      { type: "p", text: "Never mutate state directly. Always use the setter function. State updates are asynchronous — React batches them for performance." },
    ],
  },
  {
    slug: "effects",
    topicId: "react",
    title: "useEffect",
    summary: "Run side effects after render — fetch data, timers, subscriptions.",
    minutes: 14,
    order: 6,
    blocks: [
      { type: "code", code: 'import { useState, useEffect } from "react";\n\nfunction Timer() {\n  const [seconds, setSeconds] = useState(0);\n\n  useEffect(() => {\n    const id = setInterval(() => setSeconds(s => s + 1), 1000);\n    return () => clearInterval(id); // cleanup\n  }, []);\n\n  return <p>{seconds}s</p>;\n}' },
      { type: "p", text: "The dependency array [] means run once on mount. [value] means re-run when value changes. Always clean up timers and listeners in the return function." },
    ],
  },
  {
    slug: "lists-and-keys",
    topicId: "react",
    title: "Lists and Keys",
    summary: "Render arrays of data with .map() and stable keys.",
    minutes: 10,
    order: 7,
    blocks: [
      { type: "code", code: 'const lessons = [\n  { id: 1, title: "Variables" },\n  { id: 2, title: "Loops" },\n];\n\nfunction LessonList() {\n  return (\n    <ul>\n      {lessons.map(lesson => (\n        <li key={lesson.id}>{lesson.title}</li>\n      ))}\n    </ul>\n  );\n}' },
      { type: "p", text: "key helps React track which items changed. Use a unique stable id — not the array index if items can be reordered or deleted." },
    ],
  },
  {
    slug: "forms-and-events",
    topicId: "react",
    title: "Forms and Events",
    summary: "Handle input, submit forms, and controlled components.",
    minutes: 14,
    order: 8,
    blocks: [
      { type: "code", code: 'function LoginForm() {\n  const [email, setEmail] = useState("");\n\n  function handleSubmit(e) {\n    e.preventDefault();\n    console.log(email);\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <input\n        value={email}\n        onChange={e => setEmail(e.target.value)}\n        placeholder="Email"\n      />\n      <button type="submit">Log in</button>\n    </form>\n  );\n}' },
      { type: "p", text: "A controlled input's value comes from state. onChange updates state on every keystroke. Always call e.preventDefault() on submit to stop a page reload." },
    ],
  },
  {
    slug: "conditional-rendering",
    topicId: "react",
    title: "Conditional Rendering",
    summary: "Show different UI based on state.",
    minutes: 10,
    order: 9,
    blocks: [
      { type: "code", code: 'function Dashboard({ user }) {\n  if (!user) return <p>Please log in.</p>;\n\n  return (\n    <div>\n      <h1>Welcome, {user.name}</h1>\n      {user.isPremium && <Badge>Pro</Badge>}\n    </div>\n  );\n}' },
      { type: "p", text: "Use if/return, && for simple show/hide, or ternary for two options. Keep conditions readable." },
    ],
  },
  {
    slug: "project-structure",
    topicId: "react",
    title: "Project Structure & Next Steps",
    summary: "Folders, hooks, and where to go after the basics.",
    minutes: 10,
    order: 10,
    blocks: [
      { type: "p", text: "A typical React project separates components, hooks, utils, and pages. One component per file is a good default." },
      { type: "ul", items: ["components/ — reusable UI pieces", "hooks/ — custom hooks like useAuth", "pages/ or app/ — routes (Next.js)", "lib/ — helpers and API calls"] },
      { type: "p", text: "Next topics to learn: React Router or Next.js routing, Context API, custom hooks, and a UI library like Tailwind CSS." },
    ],
  },
];
