import type { SimpleIcon } from "simple-icons";
import {
  siPython,
  siJavascript,
  siTypescript,
  siOpenjdk,
  siC,
  siCplusplus,
  siDotnet,
  siGo,
  siRust,
  siPhp,
  siRuby,
  siSwift,
  siKotlin,
  siR,
  siGnubash,
  siReact,
  siHtml5,
  siCss,
  siPostgresql,
  siMysql,
  siSqlite,
  siMongodb,
  siSupabase,
  siMariadb,
  siRedis,
  siFirebase,
  siDocker,
  siKubernetes,
  siNodedotjs,
  siDart,
  siFlutter,
  siLua,
  siScratch,
  siGraphql,
  siApachecassandra,
  siApachecouchdb,
  siCouchbase,
  siElasticsearch,
  siNeo4j,
  siSnowflake,
  siDatabricks,
  siDuckdb,
  siCockroachlabs,
  siTidb,
  siAngular,
  siVuedotjs,
  siSvelte,
  siNextdotjs,
  siExpress,
  siDjango,
  siFlask,
  siRubyonrails,
  siLaravel,
  siSpring,
  siUnity,
  siUnrealengine,
  siGit,
  siGithub,
  siGitlab,
  siGooglecloud,
  siVercel,
  siNetlify,
  siTerraform,
  siAnsible,
  siLinux,
  siUbuntu,
  siDebian,
  siMacos,
  siAndroid,
  siIos,
  siPerl,
  siScala,
  siHaskell,
  siClojure,
  siElixir,
  siErlang,
  siJulia,
  siXml,
  siJson,
  siYaml,
} from "simple-icons";

const ICON_BY_SLUG = new Map<string, SimpleIcon>([
  ["python", siPython],
  ["javascript", siJavascript],
  ["typescript", siTypescript],
  ["openjdk", siOpenjdk],
  ["c", siC],
  ["cplusplus", siCplusplus],
  ["dotnet", siDotnet],
  ["go", siGo],
  ["rust", siRust],
  ["php", siPhp],
  ["ruby", siRuby],
  ["swift", siSwift],
  ["kotlin", siKotlin],
  ["r", siR],
  ["gnubash", siGnubash],
  ["react", siReact],
  ["html5", siHtml5],
  ["css", siCss],
  ["postgresql", siPostgresql],
  ["mysql", siMysql],
  ["sqlite", siSqlite],
  ["mongodb", siMongodb],
  ["supabase", siSupabase],
  ["mariadb", siMariadb],
  ["redis", siRedis],
  ["firebase", siFirebase],
  ["docker", siDocker],
  ["kubernetes", siKubernetes],
  ["nodedotjs", siNodedotjs],
  ["dart", siDart],
  ["flutter", siFlutter],
  ["lua", siLua],
  ["scratch", siScratch],
  ["graphql", siGraphql],
  ["apachecassandra", siApachecassandra],
  ["apachecouchdb", siApachecouchdb],
  ["couchbase", siCouchbase],
  ["elasticsearch", siElasticsearch],
  ["neo4j", siNeo4j],
  ["snowflake", siSnowflake],
  ["databricks", siDatabricks],
  ["duckdb", siDuckdb],
  ["cockroachlabs", siCockroachlabs],
  ["tidb", siTidb],
  ["angular", siAngular],
  ["vuedotjs", siVuedotjs],
  ["svelte", siSvelte],
  ["nextdotjs", siNextdotjs],
  ["express", siExpress],
  ["django", siDjango],
  ["flask", siFlask],
  ["rubyonrails", siRubyonrails],
  ["laravel", siLaravel],
  ["spring", siSpring],
  ["unity", siUnity],
  ["unrealengine", siUnrealengine],
  ["git", siGit],
  ["github", siGithub],
  ["gitlab", siGitlab],
  ["googlecloud", siGooglecloud],
  ["vercel", siVercel],
  ["netlify", siNetlify],
  ["terraform", siTerraform],
  ["ansible", siAnsible],
  ["linux", siLinux],
  ["ubuntu", siUbuntu],
  ["debian", siDebian],
  ["macos", siMacos],
  ["android", siAndroid],
  ["ios", siIos],
  ["perl", siPerl],
  ["scala", siScala],
  ["haskell", siHaskell],
  ["clojure", siClojure],
  ["elixir", siElixir],
  ["erlang", siErlang],
  ["julia", siJulia],
  ["xml", siXml],
  ["json", siJson],
  ["yaml", siYaml],
]);

export function getSimpleIcon(slug: string): SimpleIcon | undefined {
  return ICON_BY_SLUG.get(slug);
}
